[package]
name = "brot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
num-complex = "0.4.0"
prisma = "0.1.1"
angular-units = "0.2.4"
rayon = "1.5.1"
egui = "0.17.0"